name: Sync Fork Daily

on:
  schedule:
    # 每天 UTC 00:00 执行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Sync Upstream
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git
          git fetch upstream
          git checkout master
          git merge upstream/master --no-edit
          git push origin master
